// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Zora from "zora";
import * as Arrays from "../../../src/Arrays.mjs";

function testEqual(t, name, lhs, rhs) {
  t.test(name, async t => {
    t.equal(lhs, rhs, name);
  });
}

Zora.test("array of strings", t => {
  let data = [
    "first",
    "second",
    "third",
    "fourth",
    "fifth"
  ];
  let json = [
    "first",
    "second",
    "third",
    "fourth",
    "fifth"
  ];
  let encoded = Arrays.stringArray_encode(data);
  testEqual(t, "encode string array", encoded, json);
  let decoded = Arrays.stringArray_decode(json);
  testEqual(t, "decode string array preserves order", decoded, {
    TAG: "Ok",
    _0: data
  });
});

Zora.test("array of ints", t => {
  let data = [
    1,
    2,
    3,
    4,
    5
  ];
  let json = [
    1.0,
    2.0,
    3.0,
    4.0,
    5.0
  ];
  let encoded = Arrays.intArray_encode(data);
  testEqual(t, "encode int array", encoded, json);
  let decoded = Arrays.intArray_decode(json);
  testEqual(t, "decode int array preserves order", decoded, {
    TAG: "Ok",
    _0: data
  });
});

Zora.test("array of floats", t => {
  let data = [
    1.1,
    2.2,
    3.3,
    4.4,
    5.5
  ];
  let json = [
    1.1,
    2.2,
    3.3,
    4.4,
    5.5
  ];
  let encoded = Arrays.floatArray_encode(data);
  testEqual(t, "encode float array", encoded, json);
  let decoded = Arrays.floatArray_decode(json);
  testEqual(t, "decode float array preserves order", decoded, {
    TAG: "Ok",
    _0: data
  });
});

Zora.test("array of bools", t => {
  let data = [
    true,
    false,
    true,
    false,
    true
  ];
  let json = [
    true,
    false,
    true,
    false,
    true
  ];
  let encoded = Arrays.boolArray_encode(data);
  testEqual(t, "encode bool array", encoded, json);
  let decoded = Arrays.boolArray_decode(json);
  testEqual(t, "decode bool array preserves order", decoded, {
    TAG: "Ok",
    _0: data
  });
});

Zora.test("array of records", t => {
  let data = [
    {
      id: 1,
      name: "first"
    },
    {
      id: 2,
      name: "second"
    },
    {
      id: 3,
      name: "third"
    }
  ];
  let json = [
    {
      id: 1.0,
      name: "first"
    },
    {
      id: 2.0,
      name: "second"
    },
    {
      id: 3.0,
      name: "third"
    }
  ];
  let encoded = Arrays.recordArray_encode(data);
  testEqual(t, "encode record array", encoded, json);
  let decoded = Arrays.recordArray_decode(json);
  testEqual(t, "decode record array preserves order", decoded, {
    TAG: "Ok",
    _0: data
  });
});

Zora.test("nested arrays", t => {
  let data = [
    [
      1,
      2
    ],
    [
      3,
      4
    ],
    [
      5,
      6
    ]
  ];
  let json = [
    [
      1.0,
      2.0
    ],
    [
      3.0,
      4.0
    ],
    [
      5.0,
      6.0
    ]
  ];
  let encoded = Arrays.nestedArray_encode(data);
  testEqual(t, "encode nested array", encoded, json);
  let decoded = Arrays.nestedArray_decode(json);
  testEqual(t, "decode nested array preserves order", decoded, {
    TAG: "Ok",
    _0: data
  });
});

Zora.test("empty array", t => {
  let data = [];
  let json = [];
  let encoded = Arrays.stringArray_encode(data);
  testEqual(t, "encode empty array", encoded, json);
  let decoded = Arrays.stringArray_decode(json);
  testEqual(t, "decode empty array", decoded, {
    TAG: "Ok",
    _0: data
  });
});

Zora.test("single element array", t => {
  let data = ["only"];
  let json = ["only"];
  let encoded = Arrays.stringArray_encode(data);
  testEqual(t, "encode single element array", encoded, json);
  let decoded = Arrays.stringArray_decode(json);
  testEqual(t, "decode single element array", decoded, {
    TAG: "Ok",
    _0: data
  });
});

export {
  testEqual,
}
/*  Not a pure module */
