// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Zora from "zora";
import * as Dicts from "../../../src/Dicts.mjs";

function testEqual(t, name, lhs, rhs) {
  t.test(name, async t => {
    t.equal(lhs, rhs, name);
  });
}

Zora.test("dict<string>", t => {
  let data = {
    key1: "value1",
    key2: "value2"
  };
  let json = {
    key1: "value1",
    key2: "value2"
  };
  let encoded = Dicts.stringDict_encode(data);
  testEqual(t, "encode string dict", encoded, json);
  let decoded = Dicts.stringDict_decode(json);
  testEqual(t, "decode string dict", decoded, {
    TAG: "Ok",
    _0: data
  });
});

Zora.test("dict<int>", t => {
  let data = {
    a: 1,
    b: 2,
    c: 3
  };
  let json = {
    a: 1.0,
    b: 2.0,
    c: 3.0
  };
  let encoded = Dicts.intDict_encode(data);
  testEqual(t, "encode int dict", encoded, json);
  let decoded = Dicts.intDict_decode(json);
  testEqual(t, "decode int dict", decoded, {
    TAG: "Ok",
    _0: data
  });
});

Zora.test("dict<inner>", t => {
  let data = {
    first: {
      id: 1,
      name: "Alice"
    },
    second: {
      id: 2,
      name: "Bob"
    }
  };
  let json = {
    first: {
      id: 1.0,
      name: "Alice"
    },
    second: {
      id: 2.0,
      name: "Bob"
    }
  };
  let encoded = Dicts.innerDict_encode(data);
  testEqual(t, "encode inner dict", encoded, json);
  let decoded = Dicts.innerDict_decode(json);
  testEqual(t, "decode inner dict", decoded, {
    TAG: "Ok",
    _0: data
  });
});

Zora.test("empty dict", t => {
  let data = {};
  let json = {};
  let encoded = Dicts.stringDict_encode(data);
  testEqual(t, "encode empty dict", encoded, json);
  let decoded = Dicts.stringDict_decode(json);
  testEqual(t, "decode empty dict", decoded, {
    TAG: "Ok",
    _0: data
  });
});

Zora.test("Dict.t<string>", t => {
  let data = {
    foo: "bar"
  };
  let json = {
    foo: "bar"
  };
  let encoded = Dicts.dictT_encode(data);
  testEqual(t, "encode Dict.t", encoded, json);
  let decoded = Dicts.dictT_decode(json);
  testEqual(t, "decode Dict.t", decoded, {
    TAG: "Ok",
    _0: data
  });
});

export {
  testEqual,
}
/*  Not a pure module */
