// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Zora from "zora";
import * as Dicts from "../../../src/Dicts.mjs";

function testEqual(t, name, lhs, rhs) {
  t.test(name, async t => {
    t.equal(lhs, rhs, name);
  });
}

Zora.test("dict<string>", t => {
  let sample = {
    key1: "value1",
    key2: "value2",
    key3: "value3"
  };
  let sampleJson = sample;
  let sampleRecord = {
    key1: "value1",
    key2: "value2",
    key3: "value3"
  };
  let encoded = Dicts.stringDict_encode(sampleRecord);
  testEqual(t, `encode`, encoded, sampleJson);
  let decoded = Dicts.stringDict_decode(sampleJson);
  testEqual(t, `decode`, decoded, {
    TAG: "Ok",
    _0: sampleRecord
  });
});

Zora.test("dict<string> empty", t => {
  let sample = {};
  let sampleJson = sample;
  let sampleRecord = {};
  let encoded = Dicts.stringDict_encode(sampleRecord);
  testEqual(t, `encode empty dict`, encoded, sampleJson);
  let decoded = Dicts.stringDict_decode(sampleJson);
  testEqual(t, `decode empty dict`, decoded, {
    TAG: "Ok",
    _0: sampleRecord
  });
});

Zora.test("dict<int>", t => {
  let sample = {
    a: 1.0,
    b: 2.0,
    c: 42.0
  };
  let sampleJson = sample;
  let sampleRecord = {
    a: 1,
    b: 2,
    c: 42
  };
  let encoded = Dicts.intDict_encode(sampleRecord);
  testEqual(t, `encode`, encoded, sampleJson);
  let decoded = Dicts.intDict_decode(sampleJson);
  testEqual(t, `decode`, decoded, {
    TAG: "Ok",
    _0: sampleRecord
  });
});

Zora.test("dict<inner>", t => {
  let sample = {
    item1: {
      name: "first",
      value: 10.0
    },
    item2: {
      name: "second",
      value: 20.0
    }
  };
  let sampleJson = sample;
  let sampleRecord = {
    item1: {
      name: "first",
      value: 10
    },
    item2: {
      name: "second",
      value: 20
    }
  };
  let encoded = Dicts.recordDict_encode(sampleRecord);
  testEqual(t, `encode`, encoded, sampleJson);
  let decoded = Dicts.recordDict_decode(sampleJson);
  testEqual(t, `decode`, decoded, {
    TAG: "Ok",
    _0: sampleRecord
  });
});

export {
  testEqual,
}
/*  Not a pure module */
