// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Zora from "zora";
import * as EncodeDecode from "../../../src/EncodeDecode.mjs";

function testEqual(t, name, lhs, rhs) {
  t.test(name, async t => {
    t.equal(lhs, rhs, name);
  });
}

Zora.test("encode only", t => {
  let sample = {
    name: "Alice",
    nickname: "Ecila"
  };
  let sampleJson = sample;
  let encoded = EncodeDecode.te_encode({
    name: "Alice",
    nickname: "Ecila"
  });
  testEqual(t, "encode", encoded, sampleJson);
});

Zora.test("decode only", t => {
  let sample = {
    name: "Alice",
    nickname: "Ecila"
  };
  let sampleJson = sample;
  let decoded = EncodeDecode.td_decode(sampleJson);
  testEqual(t, "decode", decoded, {
    TAG: "Ok",
    _0: {
      name: "Alice",
      nickname: "Ecila"
    }
  });
});

export {
  testEqual,
}
/*  Not a pure module */
