// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Zora from "zora";
import * as EncodeDecode from "../../../src/EncodeDecode.mjs";

function testEqual(t, name, lhs, rhs) {
  t.test(name, (async function (t) {
          t.equal(lhs, rhs, name);
        }));
}

Zora.test("encode only", (function (t) {
        var sample = {};
        sample["name"] = "Alice";
        sample["nickname"] = "Ecila";
        var encoded = EncodeDecode.te_encode({
              name: "Alice",
              nickname: "Ecila"
            });
        testEqual(t, "encode", encoded, sample);
      }));

Zora.test("decode only", (function (t) {
        var sample = {};
        sample["name"] = "Alice";
        sample["nickname"] = "Ecila";
        var decoded = EncodeDecode.td_decode(sample);
        testEqual(t, "decode", decoded, {
              TAG: "Ok",
              _0: {
                name: "Alice",
                nickname: "Ecila"
              }
            });
      }));

export {
  testEqual ,
}
/*  Not a pure module */
