// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Zora from "zora";
import * as NestedModules from "../../../src/NestedModules.mjs";

function testEqual(t, name, lhs, rhs) {
  t.test(name, async t => {
    t.equal(lhs, rhs, name);
  });
}

Zora.test("nested module Inner.t encode/decode", t => {
  let sample = {
    name: "test",
    value: 42.0
  };
  let sampleJson = sample;
  let sampleRecord = {
    name: "test",
    value: 42
  };
  let encoded = NestedModules.Inner.t_encode(sampleRecord);
  testEqual(t, `encode`, encoded, sampleJson);
  let decoded = NestedModules.Inner.t_decode(sampleJson);
  testEqual(t, `decode`, decoded, {
    TAG: "Ok",
    _0: sampleRecord
  });
});

Zora.test("deeply nested module Outer.Nested.t encode/decode", t => {
  let sample = {
    label: "nested",
    count: 3.14
  };
  let sampleJson = sample;
  let sampleRecord = {
    label: "nested",
    count: 3.14
  };
  let encoded = NestedModules.Outer.Nested.t_encode(sampleRecord);
  testEqual(t, `encode`, encoded, sampleJson);
  let decoded = NestedModules.Outer.Nested.t_decode(sampleJson);
  testEqual(t, `decode`, decoded, {
    TAG: "Ok",
    _0: sampleRecord
  });
});

Zora.test("nested module Outer.wrapper with references to other nested modules", t => {
  let sample = {
    inner: {
      name: "inner-test",
      value: 100.0
    },
    nested: {
      label: "nested-test",
      count: 2.71
    }
  };
  let sampleJson = sample;
  let sampleRecord = {
    inner: {
      name: "inner-test",
      value: 100
    },
    nested: {
      label: "nested-test",
      count: 2.71
    }
  };
  let encoded = NestedModules.Outer.wrapper_encode(sampleRecord);
  testEqual(t, `encode`, encoded, sampleJson);
  let decoded = NestedModules.Outer.wrapper_decode(sampleJson);
  testEqual(t, `decode`, decoded, {
    TAG: "Ok",
    _0: sampleRecord
  });
});

Zora.test("top-level combined type with nested module references", t => {
  let sample = {
    inner: {
      name: "combined-inner",
      value: 200.0
    },
    nested: {
      label: "combined-nested",
      count: 1.41
    }
  };
  let sampleJson = sample;
  let sampleRecord = {
    inner: {
      name: "combined-inner",
      value: 200
    },
    nested: {
      label: "combined-nested",
      count: 1.41
    }
  };
  let encoded = NestedModules.combined_encode(sampleRecord);
  testEqual(t, `encode`, encoded, sampleJson);
  let decoded = NestedModules.combined_decode(sampleJson);
  testEqual(t, `decode`, decoded, {
    TAG: "Ok",
    _0: sampleRecord
  });
});

export {
  testEqual,
}
/*  Not a pure module */
