#!/usr/bin/env sh

# Get the directory of the script to work from.
DIR=$(dirname "$0")

if [ -f $DIR/src/_build/default/bin/bin.exe ]; then
    # Use the dev build
    $DIR/src/_build/default/bin/bin.exe "$@"
elif [ "$(uname)" = "Darwin" ]; then
    # Run the Mac PPX
    chmod +x "$DIR/ppx-osx.exe" 2>/dev/null
    "$DIR/ppx-osx.exe" "$@"
elif [ "$(expr substr $(uname -s) 1 5)" = "Linux" ]; then
    # Run the Linux PPX
    chmod +x "$DIR/ppx-linux.exe" 2>/dev/null
    "$DIR/ppx-linux.exe" "$@"
else
    echo "No release available for '$(uname)'"
    exit 1
fi
