// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Records_test from "./spec/records_test.mjs";
import * as Variants_test from "./spec/variants_test.mjs";
import * as Polyvariants_test from "./spec/polyvariants_test.mjs";
import * as Encode_decode_test from "./spec/encode_decode_test.mjs";
import * as Optional_field_records_test from "./spec/optional_field_records_test.mjs";

let deepEqualWithBigInt = Records_test.deepEqualWithBigInt;

let testEqual = Variants_test.testEqual;

export {
  deepEqualWithBigInt,
  testEqual,
}
/* Records_test Not a pure module */
