// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Spice from "./Spice.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

function stringArray_encode(v) {
  return Spice.arrayToJson(Spice.stringToJson, v);
}

function stringArray_decode(v) {
  return Spice.arrayFromJson(Spice.stringFromJson, v);
}

function intArray_encode(v) {
  return Spice.arrayToJson(Spice.intToJson, v);
}

function intArray_decode(v) {
  return Spice.arrayFromJson(Spice.intFromJson, v);
}

function floatArray_encode(v) {
  return Spice.arrayToJson(Spice.floatToJson, v);
}

function floatArray_decode(v) {
  return Spice.arrayFromJson(Spice.floatFromJson, v);
}

function boolArray_encode(v) {
  return Spice.arrayToJson(Spice.boolToJson, v);
}

function boolArray_decode(v) {
  return Spice.arrayFromJson(Spice.boolFromJson, v);
}

function recordItem_encode(v) {
  return Object.fromEntries(Spice.filterOptional([
    [
      "id",
      Spice.intToJson(v.id)
    ],
    [
      "name",
      Spice.stringToJson(v.name)
    ]
  ]));
}

function recordItem_decode(v) {
  if (typeof v !== "object" || v === null || Array.isArray(v)) {
    return Spice.error(undefined, "Not an object", v);
  }
  let id = Stdlib_Option.getOr(Stdlib_Option.map(v["id"], Spice.intFromJson), Spice.error(undefined, "id" + " missing", v));
  if (id.TAG === "Ok") {
    let name = Stdlib_Option.getOr(Stdlib_Option.map(v["name"], Spice.stringFromJson), Spice.error(undefined, "name" + " missing", v));
    if (name.TAG === "Ok") {
      return {
        TAG: "Ok",
        _0: {
          id: id._0,
          name: name._0
        }
      };
    }
    let e = name._0;
    return Spice.error("." + ("name" + e.path), e.message, e.value);
  }
  let e$1 = id._0;
  return Spice.error("." + ("id" + e$1.path), e$1.message, e$1.value);
}

function recordArray_encode(v) {
  return Spice.arrayToJson(recordItem_encode, v);
}

function recordArray_decode(v) {
  return Spice.arrayFromJson(recordItem_decode, v);
}

function nestedArray_encode(v) {
  return Spice.arrayToJson(extra => Spice.arrayToJson(Spice.intToJson, extra), v);
}

function nestedArray_decode(v) {
  return Spice.arrayFromJson(extra => Spice.arrayFromJson(Spice.intFromJson, extra), v);
}

export {
  stringArray_encode,
  stringArray_decode,
  intArray_encode,
  intArray_decode,
  floatArray_encode,
  floatArray_decode,
  boolArray_encode,
  boolArray_decode,
  recordItem_encode,
  recordItem_decode,
  recordArray_encode,
  recordArray_decode,
  nestedArray_encode,
  nestedArray_decode,
}
/* No side effect */
