// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Spice from "./Spice.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

function stringDict_encode(v) {
  return Spice.dictToJson(Spice.stringToJson, v);
}

function stringDict_decode(v) {
  return Spice.dictFromJson(Spice.stringFromJson, v);
}

function intDict_encode(v) {
  return Spice.dictToJson(Spice.intToJson, v);
}

function intDict_decode(v) {
  return Spice.dictFromJson(Spice.intFromJson, v);
}

function inner_encode(v) {
  return Object.fromEntries(Spice.filterOptional([
    [
      "name",
      Spice.stringToJson(v.name)
    ],
    [
      "value",
      Spice.intToJson(v.value)
    ]
  ]));
}

function inner_decode(v) {
  if (typeof v !== "object" || v === null || Array.isArray(v)) {
    return Spice.error(undefined, "Not an object", v);
  }
  let name_result = Stdlib_Option.getOr(Stdlib_Option.map(v["name"], Spice.stringFromJson), Spice.error(undefined, "name" + " missing", v));
  let value_result = Stdlib_Option.getOr(Stdlib_Option.map(v["value"], Spice.intFromJson), Spice.error(undefined, "value" + " missing", v));
  if (name_result.TAG === "Ok") {
    if (value_result.TAG === "Ok") {
      return {
        TAG: "Ok",
        _0: {
          name: name_result._0,
          value: value_result._0
        }
      };
    }
    let e = value_result._0;
    return Spice.error("value", e.message, e.value);
  }
  let e$1 = name_result._0;
  return Spice.error("name", e$1.message, e$1.value);
}

function recordDict_encode(v) {
  return Spice.dictToJson(inner_encode, v);
}

function recordDict_decode(v) {
  return Spice.dictFromJson(inner_decode, v);
}

export {
  stringDict_encode,
  stringDict_decode,
  intDict_encode,
  intDict_decode,
  inner_encode,
  inner_decode,
  recordDict_encode,
  recordDict_decode,
}
/* No side effect */
