// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Spice from "./Spice.mjs";
import * as Js_dict from "rescript/lib/es6/Js_dict.js";
import * as Belt_Option from "rescript/lib/es6/Belt_Option.js";

function te_encode(v) {
  let extra = v.nickname;
  return Js_dict.fromArray(Spice.filterOptional([
    [
      "name",
      Spice.stringToJson(v.name)
    ],
    [
      "nickname",
      Spice.optionToJson(Spice.stringToJson, extra)
    ]
  ]));
}

function td_decode(v) {
  if (!Array.isArray(v) && (v === null || typeof v !== "object") && typeof v !== "number" && typeof v !== "string" && typeof v !== "boolean") {
    return Spice.error(undefined, "Not an object", v);
  }
  if (!(typeof v === "object" && !Array.isArray(v))) {
    return Spice.error(undefined, "Not an object", v);
  }
  let name_result = Belt_Option.getWithDefault(Belt_Option.map(Js_dict.get(v, "name"), Spice.stringFromJson), Spice.error(undefined, "name" + " missing", v));
  let nickname_result = Belt_Option.getWithDefault(Belt_Option.map(Js_dict.get(v, "nickname"), extra => Spice.optionFromJson(Spice.stringFromJson, extra)), {
    TAG: "Ok",
    _0: undefined
  });
  if (name_result.TAG === "Ok") {
    let name = name_result._0;
    if (nickname_result.TAG === "Ok") {
      let nickname = nickname_result._0;
      if (nickname !== undefined) {
        return {
          TAG: "Ok",
          _0: {
            name: name,
            nickname: nickname
          }
        };
      } else {
        return {
          TAG: "Ok",
          _0: {
            name: name
          }
        };
      }
    }
    let e = nickname_result._0;
    return Spice.error("nickname", e.message, e.value);
  }
  let e$1 = name_result._0;
  return Spice.error("name", e$1.message, e$1.value);
}

export {
  te_encode,
  td_decode,
}
/* No side effect */
