// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Spice from "./Spice.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

function t_encode(v) {
  let extra = v.f1;
  let extra$1 = v.f2;
  let extra$2 = v.f3;
  let extra$3 = v.f4;
  let extra$4 = v.f5;
  let extra$5 = v.f6;
  let extra$6 = v.f7;
  let extra$7 = v.f8;
  let extra$8 = v.f9;
  let extra$9 = v.f10;
  let extra$10 = v.f11;
  let extra$11 = v.f12;
  let extra$12 = v.f13;
  let extra$13 = v.f14;
  let extra$14 = v.f15;
  let extra$15 = v.f16;
  let extra$16 = v.f17;
  let extra$17 = v.f18;
  let extra$18 = v.f19;
  let extra$19 = v.f20;
  let extra$20 = v.f21;
  let extra$21 = v.f22;
  let extra$22 = v.f23;
  let extra$23 = v.f24;
  let extra$24 = v.f25;
  let extra$25 = v.f26;
  return Object.fromEntries(Spice.filterOptional([
    [
      "f1",
      Spice.optionToJson(Spice.stringToJson, extra)
    ],
    [
      "f2",
      Spice.optionToJson(Spice.stringToJson, extra$1)
    ],
    [
      "f3",
      Spice.optionToJson(Spice.stringToJson, extra$2)
    ],
    [
      "f4",
      Spice.optionToJson(Spice.stringToJson, extra$3)
    ],
    [
      "f5",
      Spice.optionToJson(Spice.stringToJson, extra$4)
    ],
    [
      "f6",
      Spice.optionToJson(Spice.stringToJson, extra$5)
    ],
    [
      "f7",
      Spice.optionToJson(Spice.stringToJson, extra$6)
    ],
    [
      "f8",
      Spice.optionToJson(Spice.stringToJson, extra$7)
    ],
    [
      "f9",
      Spice.optionToJson(Spice.stringToJson, extra$8)
    ],
    [
      "f10",
      Spice.optionToJson(Spice.stringToJson, extra$9)
    ],
    [
      "f11",
      Spice.optionToJson(Spice.stringToJson, extra$10)
    ],
    [
      "f12",
      Spice.optionToJson(Spice.stringToJson, extra$11)
    ],
    [
      "f13",
      Spice.optionToJson(Spice.stringToJson, extra$12)
    ],
    [
      "f14",
      Spice.optionToJson(Spice.stringToJson, extra$13)
    ],
    [
      "f15",
      Spice.optionToJson(Spice.stringToJson, extra$14)
    ],
    [
      "f16",
      Spice.optionToJson(Spice.stringToJson, extra$15)
    ],
    [
      "f17",
      Spice.optionToJson(Spice.stringToJson, extra$16)
    ],
    [
      "f18",
      Spice.optionToJson(Spice.stringToJson, extra$17)
    ],
    [
      "f19",
      Spice.optionToJson(Spice.stringToJson, extra$18)
    ],
    [
      "f20",
      Spice.optionToJson(Spice.stringToJson, extra$19)
    ],
    [
      "f21",
      Spice.optionToJson(Spice.stringToJson, extra$20)
    ],
    [
      "f22",
      Spice.optionToJson(Spice.stringToJson, extra$21)
    ],
    [
      "f23",
      Spice.optionToJson(Spice.stringToJson, extra$22)
    ],
    [
      "f24",
      Spice.optionToJson(Spice.stringToJson, extra$23)
    ],
    [
      "f25",
      Spice.optionToJson(Spice.stringToJson, extra$24)
    ],
    [
      "f26",
      Spice.optionToJson(Spice.stringToJson, extra$25)
    ]
  ]));
}

function t_decode(v) {
  if (typeof v !== "object" || v === null || Array.isArray(v)) {
    return Spice.error(undefined, "Not an object", v);
  }
  let f1 = Stdlib_Option.getOr(Stdlib_Option.map(v["f1"], extra => Spice.optionFromJson(Spice.stringFromJson, extra)), {
    TAG: "Ok",
    _0: undefined
  });
  if (f1.TAG === "Ok") {
    let f2 = Stdlib_Option.getOr(Stdlib_Option.map(v["f2"], extra => Spice.optionFromJson(Spice.stringFromJson, extra)), {
      TAG: "Ok",
      _0: undefined
    });
    if (f2.TAG === "Ok") {
      let f3 = Stdlib_Option.getOr(Stdlib_Option.map(v["f3"], extra => Spice.optionFromJson(Spice.stringFromJson, extra)), {
        TAG: "Ok",
        _0: undefined
      });
      if (f3.TAG === "Ok") {
        let f4 = Stdlib_Option.getOr(Stdlib_Option.map(v["f4"], extra => Spice.optionFromJson(Spice.stringFromJson, extra)), {
          TAG: "Ok",
          _0: undefined
        });
        if (f4.TAG === "Ok") {
          let f5 = Stdlib_Option.getOr(Stdlib_Option.map(v["f5"], extra => Spice.optionFromJson(Spice.stringFromJson, extra)), {
            TAG: "Ok",
            _0: undefined
          });
          if (f5.TAG === "Ok") {
            let f6 = Stdlib_Option.getOr(Stdlib_Option.map(v["f6"], extra => Spice.optionFromJson(Spice.stringFromJson, extra)), {
              TAG: "Ok",
              _0: undefined
            });
            if (f6.TAG === "Ok") {
              let f7 = Stdlib_Option.getOr(Stdlib_Option.map(v["f7"], extra => Spice.optionFromJson(Spice.stringFromJson, extra)), {
                TAG: "Ok",
                _0: undefined
              });
              if (f7.TAG === "Ok") {
                let f8 = Stdlib_Option.getOr(Stdlib_Option.map(v["f8"], extra => Spice.optionFromJson(Spice.stringFromJson, extra)), {
                  TAG: "Ok",
                  _0: undefined
                });
                if (f8.TAG === "Ok") {
                  let f9 = Stdlib_Option.getOr(Stdlib_Option.map(v["f9"], extra => Spice.optionFromJson(Spice.stringFromJson, extra)), {
                    TAG: "Ok",
                    _0: undefined
                  });
                  if (f9.TAG === "Ok") {
                    let f10 = Stdlib_Option.getOr(Stdlib_Option.map(v["f10"], extra => Spice.optionFromJson(Spice.stringFromJson, extra)), {
                      TAG: "Ok",
                      _0: undefined
                    });
                    if (f10.TAG === "Ok") {
                      let f11 = Stdlib_Option.getOr(Stdlib_Option.map(v["f11"], extra => Spice.optionFromJson(Spice.stringFromJson, extra)), {
                        TAG: "Ok",
                        _0: undefined
                      });
                      if (f11.TAG === "Ok") {
                        let f12 = Stdlib_Option.getOr(Stdlib_Option.map(v["f12"], extra => Spice.optionFromJson(Spice.stringFromJson, extra)), {
                          TAG: "Ok",
                          _0: undefined
                        });
                        if (f12.TAG === "Ok") {
                          let f13 = Stdlib_Option.getOr(Stdlib_Option.map(v["f13"], extra => Spice.optionFromJson(Spice.stringFromJson, extra)), {
                            TAG: "Ok",
                            _0: undefined
                          });
                          if (f13.TAG === "Ok") {
                            let f14 = Stdlib_Option.getOr(Stdlib_Option.map(v["f14"], extra => Spice.optionFromJson(Spice.stringFromJson, extra)), {
                              TAG: "Ok",
                              _0: undefined
                            });
                            if (f14.TAG === "Ok") {
                              let f15 = Stdlib_Option.getOr(Stdlib_Option.map(v["f15"], extra => Spice.optionFromJson(Spice.stringFromJson, extra)), {
                                TAG: "Ok",
                                _0: undefined
                              });
                              if (f15.TAG === "Ok") {
                                let f16 = Stdlib_Option.getOr(Stdlib_Option.map(v["f16"], extra => Spice.optionFromJson(Spice.stringFromJson, extra)), {
                                  TAG: "Ok",
                                  _0: undefined
                                });
                                if (f16.TAG === "Ok") {
                                  let f17 = Stdlib_Option.getOr(Stdlib_Option.map(v["f17"], extra => Spice.optionFromJson(Spice.stringFromJson, extra)), {
                                    TAG: "Ok",
                                    _0: undefined
                                  });
                                  if (f17.TAG === "Ok") {
                                    let f18 = Stdlib_Option.getOr(Stdlib_Option.map(v["f18"], extra => Spice.optionFromJson(Spice.stringFromJson, extra)), {
                                      TAG: "Ok",
                                      _0: undefined
                                    });
                                    if (f18.TAG === "Ok") {
                                      let f19 = Stdlib_Option.getOr(Stdlib_Option.map(v["f19"], extra => Spice.optionFromJson(Spice.stringFromJson, extra)), {
                                        TAG: "Ok",
                                        _0: undefined
                                      });
                                      if (f19.TAG === "Ok") {
                                        let f20 = Stdlib_Option.getOr(Stdlib_Option.map(v["f20"], extra => Spice.optionFromJson(Spice.stringFromJson, extra)), {
                                          TAG: "Ok",
                                          _0: undefined
                                        });
                                        if (f20.TAG === "Ok") {
                                          let f21 = Stdlib_Option.getOr(Stdlib_Option.map(v["f21"], extra => Spice.optionFromJson(Spice.stringFromJson, extra)), {
                                            TAG: "Ok",
                                            _0: undefined
                                          });
                                          if (f21.TAG === "Ok") {
                                            let f22 = Stdlib_Option.getOr(Stdlib_Option.map(v["f22"], extra => Spice.optionFromJson(Spice.stringFromJson, extra)), {
                                              TAG: "Ok",
                                              _0: undefined
                                            });
                                            if (f22.TAG === "Ok") {
                                              let f23 = Stdlib_Option.getOr(Stdlib_Option.map(v["f23"], extra => Spice.optionFromJson(Spice.stringFromJson, extra)), {
                                                TAG: "Ok",
                                                _0: undefined
                                              });
                                              if (f23.TAG === "Ok") {
                                                let f24 = Stdlib_Option.getOr(Stdlib_Option.map(v["f24"], extra => Spice.optionFromJson(Spice.stringFromJson, extra)), {
                                                  TAG: "Ok",
                                                  _0: undefined
                                                });
                                                if (f24.TAG === "Ok") {
                                                  let f25 = Stdlib_Option.getOr(Stdlib_Option.map(v["f25"], extra => Spice.optionFromJson(Spice.stringFromJson, extra)), {
                                                    TAG: "Ok",
                                                    _0: undefined
                                                  });
                                                  if (f25.TAG === "Ok") {
                                                    let f26 = Stdlib_Option.getOr(Stdlib_Option.map(v["f26"], extra => Spice.optionFromJson(Spice.stringFromJson, extra)), {
                                                      TAG: "Ok",
                                                      _0: undefined
                                                    });
                                                    if (f26.TAG === "Ok") {
                                                      return {
                                                        TAG: "Ok",
                                                        _0: {
                                                          f1: f1._0,
                                                          f2: f2._0,
                                                          f3: f3._0,
                                                          f4: f4._0,
                                                          f5: f5._0,
                                                          f6: f6._0,
                                                          f7: f7._0,
                                                          f8: f8._0,
                                                          f9: f9._0,
                                                          f10: f10._0,
                                                          f11: f11._0,
                                                          f12: f12._0,
                                                          f13: f13._0,
                                                          f14: f14._0,
                                                          f15: f15._0,
                                                          f16: f16._0,
                                                          f17: f17._0,
                                                          f18: f18._0,
                                                          f19: f19._0,
                                                          f20: f20._0,
                                                          f21: f21._0,
                                                          f22: f22._0,
                                                          f23: f23._0,
                                                          f24: f24._0,
                                                          f25: f25._0,
                                                          f26: f26._0
                                                        }
                                                      };
                                                    }
                                                    let e = f26._0;
                                                    return Spice.error("." + ("f26" + e.path), e.message, e.value);
                                                  }
                                                  let e$1 = f25._0;
                                                  return Spice.error("." + ("f25" + e$1.path), e$1.message, e$1.value);
                                                }
                                                let e$2 = f24._0;
                                                return Spice.error("." + ("f24" + e$2.path), e$2.message, e$2.value);
                                              }
                                              let e$3 = f23._0;
                                              return Spice.error("." + ("f23" + e$3.path), e$3.message, e$3.value);
                                            }
                                            let e$4 = f22._0;
                                            return Spice.error("." + ("f22" + e$4.path), e$4.message, e$4.value);
                                          }
                                          let e$5 = f21._0;
                                          return Spice.error("." + ("f21" + e$5.path), e$5.message, e$5.value);
                                        }
                                        let e$6 = f20._0;
                                        return Spice.error("." + ("f20" + e$6.path), e$6.message, e$6.value);
                                      }
                                      let e$7 = f19._0;
                                      return Spice.error("." + ("f19" + e$7.path), e$7.message, e$7.value);
                                    }
                                    let e$8 = f18._0;
                                    return Spice.error("." + ("f18" + e$8.path), e$8.message, e$8.value);
                                  }
                                  let e$9 = f17._0;
                                  return Spice.error("." + ("f17" + e$9.path), e$9.message, e$9.value);
                                }
                                let e$10 = f16._0;
                                return Spice.error("." + ("f16" + e$10.path), e$10.message, e$10.value);
                              }
                              let e$11 = f15._0;
                              return Spice.error("." + ("f15" + e$11.path), e$11.message, e$11.value);
                            }
                            let e$12 = f14._0;
                            return Spice.error("." + ("f14" + e$12.path), e$12.message, e$12.value);
                          }
                          let e$13 = f13._0;
                          return Spice.error("." + ("f13" + e$13.path), e$13.message, e$13.value);
                        }
                        let e$14 = f12._0;
                        return Spice.error("." + ("f12" + e$14.path), e$14.message, e$14.value);
                      }
                      let e$15 = f11._0;
                      return Spice.error("." + ("f11" + e$15.path), e$15.message, e$15.value);
                    }
                    let e$16 = f10._0;
                    return Spice.error("." + ("f10" + e$16.path), e$16.message, e$16.value);
                  }
                  let e$17 = f9._0;
                  return Spice.error("." + ("f9" + e$17.path), e$17.message, e$17.value);
                }
                let e$18 = f8._0;
                return Spice.error("." + ("f8" + e$18.path), e$18.message, e$18.value);
              }
              let e$19 = f7._0;
              return Spice.error("." + ("f7" + e$19.path), e$19.message, e$19.value);
            }
            let e$20 = f6._0;
            return Spice.error("." + ("f6" + e$20.path), e$20.message, e$20.value);
          }
          let e$21 = f5._0;
          return Spice.error("." + ("f5" + e$21.path), e$21.message, e$21.value);
        }
        let e$22 = f4._0;
        return Spice.error("." + ("f4" + e$22.path), e$22.message, e$22.value);
      }
      let e$23 = f3._0;
      return Spice.error("." + ("f3" + e$23.path), e$23.message, e$23.value);
    }
    let e$24 = f2._0;
    return Spice.error("." + ("f2" + e$24.path), e$24.message, e$24.value);
  }
  let e$25 = f1._0;
  return Spice.error("." + ("f1" + e$25.path), e$25.message, e$25.value);
}

export {
  t_encode,
  t_decode,
}
/* No side effect */
