// Generated by ReScript, PLEASE EDIT WITH CARE


function createUser(id, name, email) {
  return {
    id: id,
    name: name,
    email: email
  };
}

function getUserName(user) {
  return user.name;
}

function isActive(status) {
  switch (status) {
    case "Active" :
      return true;
    case "Inactive" :
    case "Pending" :
      return false;
  }
}

function colorToString(color) {
  if (color === "Blue") {
    return "blue";
  } else if (color === "Green") {
    return "green";
  } else {
    return "red";
  }
}

export {
  createUser,
  getUserName,
  isActive,
  colorToString,
}
/* No side effect */
