// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Spice from "./Spice.mjs";
import * as Js_dict from "rescript/lib/es6/Js_dict.js";
import * as Belt_Option from "rescript/lib/es6/Belt_Option.js";

function t0_encode(v) {
  let extra = v.b;
  return Js_dict.fromArray(Spice.filterOptional([
    [
      "a",
      Spice.intToJson(v.a)
    ],
    [
      "b",
      Spice.optionToJson(Spice.intToJson, extra)
    ]
  ]));
}

function t0_decode(v) {
  if (typeof v !== "object" || v === null || Array.isArray(v)) {
    return Spice.error(undefined, "Not an object", v);
  }
  let a_result = Belt_Option.getWithDefault(Belt_Option.map(Js_dict.get(v, "a"), Spice.intFromJson), Spice.error(undefined, "a" + " missing", v));
  let b_result = Belt_Option.getWithDefault(Belt_Option.map(Js_dict.get(v, "b"), extra => Spice.optionFromJson(Spice.intFromJson, extra)), {
    TAG: "Ok",
    _0: undefined
  });
  if (a_result.TAG === "Ok") {
    if (b_result.TAG === "Ok") {
      return {
        TAG: "Ok",
        _0: {
          a: a_result._0,
          b: b_result._0
        }
      };
    }
    let e = b_result._0;
    return Spice.error("b", e.message, e.value);
  }
  let e$1 = a_result._0;
  return Spice.error("a", e$1.message, e$1.value);
}

function t1_encode(v) {
  let extra = v.bs;
  return Js_dict.fromArray(Spice.filterOptional([
    [
      "a",
      Spice.intToJson(v.a)
    ],
    [
      "bs",
      Spice.optionToJson(extra => Spice.arrayToJson(Spice.intToJson, extra), extra)
    ]
  ]));
}

function t1_decode(v) {
  if (typeof v !== "object" || v === null || Array.isArray(v)) {
    return Spice.error(undefined, "Not an object", v);
  }
  let a_result = Belt_Option.getWithDefault(Belt_Option.map(Js_dict.get(v, "a"), Spice.intFromJson), Spice.error(undefined, "a" + " missing", v));
  let bs_result = Belt_Option.getWithDefault(Belt_Option.map(Js_dict.get(v, "bs"), extra => Spice.optionFromJson(extra => Spice.arrayFromJson(Spice.intFromJson, extra), extra)), {
    TAG: "Ok",
    _0: undefined
  });
  if (a_result.TAG === "Ok") {
    if (bs_result.TAG === "Ok") {
      return {
        TAG: "Ok",
        _0: {
          a: a_result._0,
          bs: bs_result._0
        }
      };
    }
    let e = bs_result._0;
    return Spice.error("bs", e.message, e.value);
  }
  let e$1 = a_result._0;
  return Spice.error("a", e$1.message, e$1.value);
}

function b_encode(v) {
  switch (v) {
    case "B0" :
      return "B0";
    case "B1" :
      return "B1";
    case "B2" :
      return "B2";
  }
}

function b_decode(v) {
  switch (typeof v) {
    case "string" :
      if ("B0" === v) {
        return {
          TAG: "Ok",
          _0: "B0"
        };
      } else if ("B1" === v) {
        return {
          TAG: "Ok",
          _0: "B1"
        };
      } else if ("B2" === v) {
        return {
          TAG: "Ok",
          _0: "B2"
        };
      } else {
        return Spice.error(undefined, "Not matched", v);
      }
    case "number" :
      return Spice.error(undefined, "Not matched", v);
    default:
      return Spice.error(undefined, "Not a JSONString", v);
  }
}

function t2_encode(v) {
  let extra = v.bs;
  return Js_dict.fromArray(Spice.filterOptional([
    [
      "a",
      Spice.intToJson(v.a)
    ],
    [
      "bs",
      Spice.optionToJson(extra => Spice.arrayToJson(b_encode, extra), extra)
    ]
  ]));
}

function t2_decode(v) {
  if (typeof v !== "object" || v === null || Array.isArray(v)) {
    return Spice.error(undefined, "Not an object", v);
  }
  let a_result = Belt_Option.getWithDefault(Belt_Option.map(Js_dict.get(v, "a"), Spice.intFromJson), Spice.error(undefined, "a" + " missing", v));
  let bs_result = Belt_Option.getWithDefault(Belt_Option.map(Js_dict.get(v, "bs"), extra => Spice.optionFromJson(extra => Spice.arrayFromJson(b_decode, extra), extra)), {
    TAG: "Ok",
    _0: undefined
  });
  if (a_result.TAG === "Ok") {
    if (bs_result.TAG === "Ok") {
      return {
        TAG: "Ok",
        _0: {
          a: a_result._0,
          bs: bs_result._0
        }
      };
    }
    let e = bs_result._0;
    return Spice.error("bs", e.message, e.value);
  }
  let e$1 = a_result._0;
  return Spice.error("a", e$1.message, e$1.value);
}

export {
  t0_encode,
  t0_decode,
  t1_encode,
  t1_decode,
  b_encode,
  b_decode,
  t2_encode,
  t2_decode,
}
/* No side effect */
