// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Spice from "./Spice.mjs";

function t_encode(v) {
  if (v === "two") {
    return `둘`;
  } else {
    return `하나`;
  }
}

function t_decode(v) {
  switch (typeof v) {
    case "string" :
      if ("하나" === v) {
        return {
          TAG: "Ok",
          _0: "one"
        };
      } else if ("둘" === v) {
        return {
          TAG: "Ok",
          _0: "two"
        };
      } else {
        return Spice.error(undefined, "Not matched", v);
      }
    case "number" :
      return Spice.error(undefined, "Not matched", v);
    default:
      return Spice.error(undefined, "Not a JSONString", v);
  }
}

function t1_encode(v) {
  if (v === "two") {
    return ["two"];
  } else {
    return ["one"];
  }
}

function t1_decode(v) {
  if (!Array.isArray(v)) {
    return Spice.error(undefined, "Not a polyvariant", v);
  }
  if (v.length === 0) {
    return Spice.error(undefined, "Expected polyvariant, found empty array", v);
  }
  let match = v[0];
  if (typeof match === "string") {
    switch (match) {
      case "one" :
        if (v.length !== 1) {
          return Spice.error(undefined, "Invalid number of arguments to polyvariant constructor", v);
        } else {
          return {
            TAG: "Ok",
            _0: "one"
          };
        }
      case "two" :
        if (v.length !== 1) {
          return Spice.error(undefined, "Invalid number of arguments to polyvariant constructor", v);
        } else {
          return {
            TAG: "Ok",
            _0: "two"
          };
        }
    }
  }
  return Spice.error(undefined, "Invalid polymorphic variant constructor", v[0]);
}

function t2_encode(v) {
  if (v === "two") {
    return 2.0;
  } else {
    return 1.0;
  }
}

function t2_decode(v) {
  switch (typeof v) {
    case "string" :
      return Spice.error(undefined, "Not matched", v);
    case "number" :
      if (1.0 === v) {
        return {
          TAG: "Ok",
          _0: "one"
        };
      } else if (2.0 === v) {
        return {
          TAG: "Ok",
          _0: "two"
        };
      } else {
        return Spice.error(undefined, "Not matched", v);
      }
    default:
      return Spice.error(undefined, "Not a JSONString", v);
  }
}

function withArgs_decode(v) {
  if (!Array.isArray(v)) {
    return Spice.error(undefined, "Not a polyvariant", v);
  }
  if (v.length === 0) {
    return Spice.error(undefined, "Expected polyvariant, found empty array", v);
  }
  let match = v[0];
  if (match === "WithArgs") {
    if (v.length !== 3) {
      return Spice.error(undefined, "Invalid number of arguments to polyvariant constructor", v);
    }
    let match$1 = Spice.intFromJson(v[1]);
    let match$2 = Spice.stringFromJson(v[2]);
    if (match$1.TAG === "Ok") {
      if (match$2.TAG === "Ok") {
        return {
          TAG: "Ok",
          _0: {
            NAME: "WithArgs",
            VAL: [
              match$1._0,
              match$2._0
            ]
          }
        };
      }
      let e = match$2._0;
      return {
        TAG: "Error",
        _0: {
          path: "[2]" + e.path,
          message: e.message,
          value: e.value
        }
      };
    }
    let e$1 = match$1._0;
    return {
      TAG: "Error",
      _0: {
        path: "[1]" + e$1.path,
        message: e$1.message,
        value: e$1.value
      }
    };
  }
  return Spice.error(undefined, "Invalid polymorphic variant constructor", v[0]);
}

export {
  t_encode,
  t_decode,
  t1_encode,
  t1_decode,
  t2_encode,
  t2_decode,
  withArgs_decode,
}
/* No side effect */
