// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Spice from "./Spice.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

function t_encode(v) {
  return Object.fromEntries(Spice.filterOptional([[
      "a",
      Spice.stringToJson(v.a)
    ]]));
}

function t_decode(v) {
  if (typeof v !== "object" || v === null || Array.isArray(v)) {
    return Spice.error(undefined, "Not an object", v);
  }
  let a = Stdlib_Option.getOr(Stdlib_Option.map(v["a"], Spice.stringFromJson), Spice.error(undefined, "a" + " missing", v));
  if (a.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: {
        a: a._0
      }
    };
  }
  let e = a._0;
  return Spice.error("a", e.message, e.value);
}

let M = {
  t_encode: t_encode,
  t_decode: t_decode
};

function response_encode(v) {
  let extra = v.data;
  let extra$1 = v.errors;
  return Object.fromEntries(Spice.filterOptional([
    [
      "data",
      Spice.optionToJson(v => v, extra)
    ],
    [
      "errors",
      Spice.optionToJson(extra => Spice.arrayToJson(t_encode, extra), extra$1)
    ]
  ]));
}

function response_decode(v) {
  if (typeof v !== "object" || v === null || Array.isArray(v)) {
    return Spice.error(undefined, "Not an object", v);
  }
  let data = Stdlib_Option.getOr(Stdlib_Option.map(v["data"], extra => Spice.optionFromJson(v => ({
    TAG: "Ok",
    _0: v
  }), extra)), {
    TAG: "Ok",
    _0: undefined
  });
  if (data.TAG === "Ok") {
    let errors = Stdlib_Option.getOr(Stdlib_Option.map(v["errors"], extra => Spice.optionFromJson(extra => Spice.arrayFromJson(t_decode, extra), extra)), {
      TAG: "Ok",
      _0: undefined
    });
    if (errors.TAG === "Ok") {
      return {
        TAG: "Ok",
        _0: {
          data: data._0,
          errors: errors._0
        }
      };
    }
    let e = errors._0;
    return Spice.error("errors", e.message, e.value);
  }
  let e$1 = data._0;
  return Spice.error("data", e$1.message, e$1.value);
}

export {
  M,
  response_encode,
  response_decode,
}
/* No side effect */
