// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Spice = require("./Spice.js");

function t_encode(v) {
  if (v === "two") {
    return "둘";
  } else {
    return "하나";
  }
}

function t_decode(v) {
  if ("하나" === v) {
    return {
            TAG: /* Ok */0,
            _0: "one"
          };
  } else if ("둘" === v) {
    return {
            TAG: /* Ok */0,
            _0: "two"
          };
  } else {
    return Spice.error(undefined, "Not matched", v);
  }
}

exports.t_encode = t_encode;
exports.t_decode = t_decode;
/* No side effect */
