// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function t_encode(v) {
  if (v) {
    return "둘";
  } else {
    return "하나";
  }
}

function t_decode(v) {
  if ("하나" === v) {
    return {
            TAG: /* Ok */0,
            _0: /* One */0
          };
  } else if ("둘" === v) {
    return {
            TAG: /* Ok */0,
            _0: /* Two */1
          };
  } else {
    return {
            TAG: /* Error */1,
            _0: "Not matched" + v
          };
  }
}

exports.t_encode = t_encode;
exports.t_decode = t_decode;
/* No side effect */
