// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function error(path, message, value) {
  var path$1 = path !== undefined ? path : "";
  return {
          TAG: /* Error */1,
          _0: {
            path: path$1,
            message: message,
            value: value
          }
        };
}

exports.error = error;
/* No side effect */
