// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Spice = require("@greenlabs/ppx-spice/src/rescript/Spice.js");
var Js_dict = require("rescript/lib/js/js_dict.js");
var Js_json = require("rescript/lib/js/js_json.js");
var Belt_Option = require("rescript/lib/js/belt_Option.js");
var Belt_Result = require("rescript/lib/js/belt_Result.js");

function language_encode(v) {
  switch (v) {
    case /* ReScript */0 :
        return "ReScript";
    case /* OCaml */1 :
        return "OCaml";
    case /* TypeScript */2 :
        return "TypeScript";
    case /* JavaScript */3 :
        return "JavaScript";
    
  }
}

function language_decode(v) {
  var str = Js_json.classify(v);
  if (typeof str === "number") {
    return Spice.error(undefined, "Not a JSONString", v);
  }
  if (str.TAG !== /* JSONString */0) {
    return Spice.error(undefined, "Not a JSONString", v);
  }
  var str$1 = str._0;
  if ("ReScript" === str$1) {
    return {
            TAG: /* Ok */0,
            _0: /* ReScript */0
          };
  } else if ("OCaml" === str$1) {
    return {
            TAG: /* Ok */0,
            _0: /* OCaml */1
          };
  } else if ("TypeScript" === str$1) {
    return {
            TAG: /* Ok */0,
            _0: /* TypeScript */2
          };
  } else if ("JavaScript" === str$1) {
    return {
            TAG: /* Ok */0,
            _0: /* JavaScript */3
          };
  } else {
    return Spice.error(undefined, "Not matched", v);
  }
}

function profile_encode(v) {
  return Js_dict.fromArray(Spice.filterOptional([
                  [
                    "name",
                    true,
                    Spice.optionToJson(Spice.stringToJson, v.name)
                  ],
                  [
                    "company",
                    true,
                    Spice.optionToJson(Spice.stringToJson, v.company)
                  ],
                  [
                    "languages",
                    true,
                    Spice.optionToJson((function (param) {
                            return Spice.arrayToJson(language_encode, param);
                          }), v.languages)
                  ]
                ]));
}

function profile_decode(v) {
  var dict = Js_json.classify(v);
  if (typeof dict === "number") {
    return Spice.error(undefined, "Not an object", v);
  }
  if (dict.TAG !== /* JSONObject */2) {
    return Spice.error(undefined, "Not an object", v);
  }
  var dict$1 = dict._0;
  var name = Spice.optionFromJson(Spice.stringFromJson, Belt_Option.getWithDefault(Js_dict.get(dict$1, "name"), null));
  if (name.TAG === /* Ok */0) {
    var company = Spice.optionFromJson(Spice.stringFromJson, Belt_Option.getWithDefault(Js_dict.get(dict$1, "company"), null));
    if (company.TAG === /* Ok */0) {
      var languages = Spice.optionFromJson((function (param) {
              return Spice.arrayFromJson(language_decode, param);
            }), Belt_Option.getWithDefault(Js_dict.get(dict$1, "languages"), null));
      if (languages.TAG === /* Ok */0) {
        return {
                TAG: /* Ok */0,
                _0: {
                  name: name._0,
                  company: company._0,
                  languages: languages._0
                }
              };
      }
      var e = languages._0;
      return {
              TAG: /* Error */1,
              _0: {
                path: ".languages" + e.path,
                message: e.message,
                value: e.value
              }
            };
    }
    var e$1 = company._0;
    return {
            TAG: /* Error */1,
            _0: {
              path: ".company" + e$1.path,
              message: e$1.message,
              value: e$1.value
            }
          };
  }
  var e$2 = name._0;
  return {
          TAG: /* Error */1,
          _0: {
            path: ".name" + e$2.path,
            message: e$2.message,
            value: e$2.value
          }
        };
}

function user_encode(v) {
  return Js_dict.fromArray(Spice.filterOptional([
                  [
                    "id",
                    false,
                    Spice.intToJson(v.id)
                  ],
                  [
                    "nickname",
                    true,
                    Spice.optionToJson(Spice.stringToJson, v.nickname)
                  ],
                  [
                    "age",
                    true,
                    Spice.optionToJson(Spice.intToJson, v.age)
                  ],
                  [
                    "profile",
                    false,
                    profile_encode(v.profile)
                  ]
                ]));
}

function user_decode(v) {
  var dict = Js_json.classify(v);
  if (typeof dict === "number") {
    return Spice.error(undefined, "Not an object", v);
  }
  if (dict.TAG !== /* JSONObject */2) {
    return Spice.error(undefined, "Not an object", v);
  }
  var dict$1 = dict._0;
  var id = Spice.intFromJson(Belt_Option.getWithDefault(Js_dict.get(dict$1, "id"), null));
  if (id.TAG === /* Ok */0) {
    var nickname = Spice.optionFromJson(Spice.stringFromJson, Belt_Option.getWithDefault(Js_dict.get(dict$1, "nickname"), null));
    if (nickname.TAG === /* Ok */0) {
      var age = Spice.optionFromJson(Spice.intFromJson, Belt_Option.getWithDefault(Js_dict.get(dict$1, "age"), null));
      if (age.TAG === /* Ok */0) {
        var profile = profile_decode(Belt_Option.getWithDefault(Js_dict.get(dict$1, "profile"), null));
        if (profile.TAG === /* Ok */0) {
          return {
                  TAG: /* Ok */0,
                  _0: {
                    id: id._0,
                    nickname: nickname._0,
                    age: age._0,
                    profile: profile._0
                  }
                };
        }
        var e = profile._0;
        return {
                TAG: /* Error */1,
                _0: {
                  path: ".profile" + e.path,
                  message: e.message,
                  value: e.value
                }
              };
      }
      var e$1 = age._0;
      return {
              TAG: /* Error */1,
              _0: {
                path: ".age" + e$1.path,
                message: e$1.message,
                value: e$1.value
              }
            };
    }
    var e$2 = nickname._0;
    return {
            TAG: /* Error */1,
            _0: {
              path: ".nickname" + e$2.path,
              message: e$2.message,
              value: e$2.value
            }
          };
  }
  var e$3 = id._0;
  return {
          TAG: /* Error */1,
          _0: {
            path: ".id" + e$3.path,
            message: e$3.message,
            value: e$3.value
          }
        };
}

var data = {
    "id": 1,
    "nickname": "bob",
    "profile": {
      "name": "Bob",
      "company": "Facebook",
      "languages": ["OCaml"]
    }
  };

var user = user_decode(data);

var json = user_encode(Belt_Result.getExn(user));

exports.language_encode = language_encode;
exports.language_decode = language_decode;
exports.profile_encode = profile_encode;
exports.profile_decode = profile_decode;
exports.user_encode = user_encode;
exports.user_decode = user_decode;
exports.data = data;
exports.user = user;
exports.json = json;
/* user Not a pure module */
