// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let Spice = require("@greenlabs/ppx-spice/src/rescript/Spice.js");
let Stdlib_Option = require("@rescript/runtime/lib/js/Stdlib_Option.js");

function language_encode(v) {
  return "ReScript";
}

function language_decode(v) {
  switch (typeof v) {
    case "string" :
      if ("ReScript" === v) {
        return {
          TAG: "Ok",
          _0: "ReScript"
        };
      } else {
        return Spice.error(undefined, "Not matched", v);
      }
    case "number" :
      return Spice.error(undefined, "Not matched", v);
    default:
      return Spice.error(undefined, "Not a JSONString", v);
  }
}

function profile_encode(v) {
  let extra = v.languages;
  return Object.fromEntries(Spice.filterOptional([[
      "languages",
      Spice.optionToJson(extra => Spice.arrayToJson(language_encode, extra), extra)
    ]]));
}

function profile_decode(v) {
  if (typeof v !== "object" || v === null || Array.isArray(v)) {
    return Spice.error(undefined, "Not an object", v);
  }
  let languages_result = Stdlib_Option.getOr(Stdlib_Option.map(v["languages"], extra => Spice.optionFromJson(extra => Spice.arrayFromJson(language_decode, extra), extra)), {
    TAG: "Ok",
    _0: undefined
  });
  if (languages_result.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: {
        languages: languages_result._0
      }
    };
  }
  let e = languages_result._0;
  return Spice.error("languages", e.message, e.value);
}

function user_encode(v) {
  return Object.fromEntries(Spice.filterOptional([[
      "profile",
      profile_encode(v.profile)
    ]]));
}

function user_decode(v) {
  if (typeof v !== "object" || v === null || Array.isArray(v)) {
    return Spice.error(undefined, "Not an object", v);
  }
  let profile_result = Stdlib_Option.getOr(Stdlib_Option.map(v["profile"], profile_decode), Spice.error(undefined, "profile" + " missing", v));
  if (profile_result.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: {
        profile: profile_result._0
      }
    };
  }
  let e = profile_result._0;
  return Spice.error("profile", e.message, e.value);
}

exports.language_encode = language_encode;
exports.language_decode = language_decode;
exports.profile_encode = profile_encode;
exports.profile_decode = profile_decode;
exports.user_encode = user_encode;
exports.user_decode = user_decode;
/* No side effect */
