// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let Spice = require("@mununki/ppx-spice/src/rescript/Spice.js");
let Stdlib_Option = require("@rescript/runtime/lib/js/Stdlib_Option.js");
let Stdlib_Result = require("@rescript/runtime/lib/js/Stdlib_Result.js");

function userRaw_encode(v) {
  return Object.fromEntries(Spice.filterOptional([
    [
      "name",
      Spice.stringToJson(v.name)
    ],
    [
      "address_street",
      Spice.stringToJson(v.address_street)
    ],
    [
      "address_number",
      Spice.intToJson(v.address_number)
    ]
  ]));
}

function userRaw_decode(v) {
  if (typeof v !== "object" || v === null || Array.isArray(v)) {
    return Spice.error(undefined, "Not an object", v);
  }
  let name = Stdlib_Option.getOr(Stdlib_Option.map(v["name"], Spice.stringFromJson), Spice.error(undefined, "name" + " missing", v));
  if (name.TAG === "Ok") {
    let address_street = Stdlib_Option.getOr(Stdlib_Option.map(v["address_street"], Spice.stringFromJson), Spice.error(undefined, "address_street" + " missing", v));
    if (address_street.TAG === "Ok") {
      let address_number = Stdlib_Option.getOr(Stdlib_Option.map(v["address_number"], Spice.intFromJson), Spice.error(undefined, "address_number" + " missing", v));
      if (address_number.TAG === "Ok") {
        return {
          TAG: "Ok",
          _0: {
            name: name._0,
            address_street: address_street._0,
            address_number: address_number._0
          }
        };
      }
      let e = address_number._0;
      return Spice.error("." + ("address_number" + e.path), e.message, e.value);
    }
    let e$1 = address_street._0;
    return Spice.error("." + ("address_street" + e$1.path), e$1.message, e$1.value);
  }
  let e$2 = name._0;
  return Spice.error("." + ("name" + e$2.path), e$2.message, e$2.value);
}

let data = {
  "name": "woonki",
  "address_street": "Munjung",
  "address_number": 8
};

let data$1 = Stdlib_Result.map(userRaw_decode(data), userRaw => ({
  name: userRaw.name,
  address: {
    street: userRaw.address_street,
    number: userRaw.address_number
  }
}));

let json = Stdlib_Result.map(data$1, user => userRaw_encode({
  name: user.name,
  address_street: user.address.street,
  address_number: user.address.number
}));

exports.userRaw_encode = userRaw_encode;
exports.userRaw_decode = userRaw_decode;
exports.data = data$1;
exports.json = json;
/* data Not a pure module */
