// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let Spice = require("@jfrolich/ppx-spice/src/rescript/Spice.js");
let Stdlib_Option = require("@rescript/runtime/lib/js/Stdlib_Option.js");
let Stdlib_Result = require("@rescript/runtime/lib/js/Stdlib_Result.js");

function profile_encode(v) {
  return [
    Spice.stringToJson(v[0]),
    Spice.intToJson(v[1])
  ];
}

function profile_decode(v) {
  if (!Array.isArray(v)) {
    return Spice.error(undefined, "Not a tuple", v);
  }
  if (v.length !== 2) {
    return Spice.error(undefined, "Incorrect cardinality", v);
  }
  let v0 = v[0];
  let v1 = v[1];
  let match = Spice.stringFromJson(v0);
  let match$1 = Spice.intFromJson(v1);
  if (match.TAG === "Ok") {
    if (match$1.TAG === "Ok") {
      return {
        TAG: "Ok",
        _0: [
          match._0,
          match$1._0
        ]
      };
    }
    let e = match$1._0;
    return {
      TAG: "Error",
      _0: {
        path: "[1]" + e.path,
        message: e.message,
        value: e.value
      }
    };
  }
  let e$1 = match._0;
  return {
    TAG: "Error",
    _0: {
      path: "[0]" + e$1.path,
      message: e$1.message,
      value: e$1.value
    }
  };
}

function user_encode(v) {
  return Object.fromEntries(Spice.filterOptional([
    [
      "id",
      Spice.intToJson(v.id)
    ],
    [
      "name",
      Spice.stringToJson(v.name)
    ],
    [
      "profile",
      profile_encode(v.profile)
    ]
  ]));
}

function user_decode(v) {
  if (typeof v !== "object" || v === null || Array.isArray(v)) {
    return Spice.error(undefined, "Not an object", v);
  }
  let id = Stdlib_Option.getOr(Stdlib_Option.map(v["id"], Spice.intFromJson), Spice.error(undefined, "id" + " missing", v));
  if (id.TAG === "Ok") {
    let name = Stdlib_Option.getOr(Stdlib_Option.map(v["name"], Spice.stringFromJson), Spice.error(undefined, "name" + " missing", v));
    if (name.TAG === "Ok") {
      let profile = Stdlib_Option.getOr(Stdlib_Option.map(v["profile"], profile_decode), Spice.error(undefined, "profile" + " missing", v));
      if (profile.TAG === "Ok") {
        return {
          TAG: "Ok",
          _0: {
            id: id._0,
            name: name._0,
            profile: profile._0
          }
        };
      }
      let e = profile._0;
      return Spice.error("profile", e.message, e.value);
    }
    let e$1 = name._0;
    return Spice.error("name", e$1.message, e$1.value);
  }
  let e$2 = id._0;
  return Spice.error("id", e$2.message, e$2.value);
}

let data = {
    "id": 1,
    "name": "woonki",
    "profile": ["mununki", 0]
  };

let user = user_decode(data);

let json = user_encode(Stdlib_Result.getOrThrow(user, undefined));

exports.profile_encode = profile_encode;
exports.profile_decode = profile_decode;
exports.user_encode = user_encode;
exports.user_decode = user_decode;
exports.data = data;
exports.user = user;
exports.json = json;
/* user Not a pure module */
