// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var Records = require("../src/Records.js");

Jest.describe("record with @spice.key", (function (param) {
        var sample = {};
        sample["spice-label"] = "sample";
        sample["spice-value"] = 1.0;
        var sampleRecord = {
          label: "sample",
          value: 1
        };
        Jest.test("encode", (function (param) {
                var encoded = Records.t_encode(sampleRecord);
                return Jest.Expect.toEqual(sample, Jest.Expect.expect(encoded));
              }));
        return Jest.test("decode", (function (param) {
                      var decoded = Records.t_decode(sample);
                      return Jest.Expect.toEqual({
                                  TAG: /* Ok */0,
                                  _0: sampleRecord
                                }, Jest.Expect.expect(decoded));
                    }));
      }));

Jest.describe("record without @spice.key", (function (param) {
        var sample = {};
        sample["label"] = "sample";
        sample["value"] = 1.0;
        var sampleRecord = {
          label: "sample",
          value: 1
        };
        Jest.test("encode", (function (param) {
                var encoded = Records.t1_encode(sampleRecord);
                return Jest.Expect.toEqual(sample, Jest.Expect.expect(encoded));
              }));
        return Jest.test("decode", (function (param) {
                      var decoded = Records.t1_decode(sample);
                      return Jest.Expect.toEqual({
                                  TAG: /* Ok */0,
                                  _0: sampleRecord
                                }, Jest.Expect.expect(decoded));
                    }));
      }));

/*  Not a pure module */
