// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var Sample1 = require("../src/sample1.js");

console.log(Sample1.t_decode);

Jest.describe("init", (function (param) {
        return Jest.test("actually running?", (function (param) {
                      return Jest.Expect.toEqual("a", Jest.Expect.expect("a"));
                    }));
      }));

/*  Not a pure module */
