// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/rescript-jest/src/jest.js");
var EncodeDecode = require("../src/EncodeDecode.js");

Jest.describe("encode only", (function () {
        var sample = {};
        sample["name"] = "Alice";
        sample["nickname"] = "Ecila";
        Jest.test("encode", (function () {
                var encoded = EncodeDecode.te_encode({
                      name: "Alice",
                      nickname: "Ecila"
                    });
                return Jest.Expect.toEqual(Jest.Expect.expect(encoded), sample);
              }));
      }));

Jest.describe("decode only", (function () {
        var sample = {};
        sample["name"] = "Alice";
        sample["nickname"] = "Ecila";
        Jest.test("decode", (function () {
                var decoded = EncodeDecode.td_decode(sample);
                return Jest.Expect.toEqual(Jest.Expect.expect(decoded), {
                            TAG: "Ok",
                            _0: {
                              name: "Alice",
                              nickname: "Ecila"
                            }
                          });
              }));
      }));

/*  Not a pure module */
