// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/rescript-jest/src/jest.js");
var Polyvariants = require("../src/Polyvariants.js");

Jest.describe("polymorphic variants with attribute", (function () {
        Jest.test("encode 하나", (function () {
                var polyvariantEncoded = Polyvariants.t_encode("one");
                return Jest.Expect.toEqual(Jest.Expect.expect(polyvariantEncoded), "하나");
              }));
        Jest.test("encode 둘", (function () {
                var polyvariantEncoded = Polyvariants.t_encode("two");
                return Jest.Expect.toEqual(Jest.Expect.expect(polyvariantEncoded), "둘");
              }));
        Jest.test("decode 하나", (function () {
                var polyvariantDecoded = Polyvariants.t_decode("하나");
                return Jest.Expect.toEqual(Jest.Expect.expect(polyvariantDecoded), {
                            TAG: "Ok",
                            _0: "one"
                          });
              }));
        Jest.test("decode 둘", (function () {
                var polyvariantDecoded = Polyvariants.t_decode("둘");
                return Jest.Expect.toEqual(Jest.Expect.expect(polyvariantDecoded), {
                            TAG: "Ok",
                            _0: "two"
                          });
              }));
      }));

Jest.describe("polymorphic variants", (function () {
        Jest.test("encode #one", (function () {
                var polyvariantEncoded = Polyvariants.t1_encode("one");
                return Jest.Expect.toEqual(Jest.Expect.expect(polyvariantEncoded), ["one"]);
              }));
        Jest.test("encode #two", (function () {
                var polyvariantEncoded = Polyvariants.t1_encode("two");
                return Jest.Expect.toEqual(Jest.Expect.expect(polyvariantEncoded), ["two"]);
              }));
        Jest.test("decode one", (function () {
                var polyvariantDecoded = Polyvariants.t1_decode(["one"]);
                return Jest.Expect.toEqual(Jest.Expect.expect(polyvariantDecoded), {
                            TAG: "Ok",
                            _0: "one"
                          });
              }));
        Jest.test("decode two", (function () {
                var polyvariantDecoded = Polyvariants.t1_decode(["two"]);
                return Jest.Expect.toEqual(Jest.Expect.expect(polyvariantDecoded), {
                            TAG: "Ok",
                            _0: "two"
                          });
              }));
      }));

/*  Not a pure module */
