// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/rescript-jest/src/jest.js");
var OptionalFieldRecords = require("../src/OptionalFieldRecords.js");

Jest.describe("optional field record", (function () {
        var sample = {};
        sample["a"] = 1;
        sample["b"] = 1;
        var sampleRecord = {
          a: 1,
          b: 1
        };
        Jest.test("encode", (function () {
                var encoded = OptionalFieldRecords.t0_encode(sampleRecord);
                return Jest.Expect.toEqual(Jest.Expect.expect(encoded), sample);
              }));
        Jest.test("decode", (function () {
                var decoded = OptionalFieldRecords.t0_decode(sample);
                return Jest.Expect.toEqual(Jest.Expect.expect(decoded), {
                            TAG: "Ok",
                            _0: sampleRecord
                          });
              }));
      }));

Jest.describe("optional field record: array<int>", (function () {
        var sample = {};
        sample["a"] = 1;
        sample["bs"] = [1];
        var sampleRecord_bs = [1];
        var sampleRecord = {
          a: 1,
          bs: sampleRecord_bs
        };
        Jest.test("encode", (function () {
                var encoded = OptionalFieldRecords.t1_encode(sampleRecord);
                return Jest.Expect.toEqual(Jest.Expect.expect(encoded), sample);
              }));
        Jest.test("decode", (function () {
                var decoded = OptionalFieldRecords.t1_decode(sample);
                return Jest.Expect.toEqual(Jest.Expect.expect(decoded), {
                            TAG: "Ok",
                            _0: sampleRecord
                          });
              }));
      }));

Jest.describe("optional field record: array<variant>", (function () {
        var sample = {};
        sample["a"] = 1;
        sample["bs"] = ["B1"];
        var sampleRecord_bs = ["B1"];
        var sampleRecord = {
          a: 1,
          bs: sampleRecord_bs
        };
        Jest.test("encode", (function () {
                var encoded = OptionalFieldRecords.t2_encode(sampleRecord);
                return Jest.Expect.toEqual(Jest.Expect.expect(encoded), sample);
              }));
        Jest.test("decode", (function () {
                var decoded = OptionalFieldRecords.t2_decode(sample);
                return Jest.Expect.toEqual(Jest.Expect.expect(decoded), {
                            TAG: "Ok",
                            _0: sampleRecord
                          });
              }));
      }));

Jest.describe("optional field record: omit array<variant>", (function () {
        var sample = {};
        sample["a"] = 1;
        var sampleRecord = {
          a: 1
        };
        Jest.test("encode", (function () {
                var encoded = OptionalFieldRecords.t2_encode(sampleRecord);
                return Jest.Expect.toEqual(Jest.Expect.expect(encoded), sample);
              }));
        Jest.test("decode", (function () {
                var decoded = OptionalFieldRecords.t2_decode(sample);
                return Jest.Expect.toEqual(Jest.Expect.expect(decoded), {
                            TAG: "Ok",
                            _0: sampleRecord
                          });
              }));
      }));

/*  Not a pure module */
