name: ppx_spice build macOS

on: [workflow_dispatch]

jobs:
  build_macos:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: src
    strategy:
      matrix:
        os: [macOS-latest]
        ocaml-compiler:
          - 4.14.0

    steps:
      - uses: actions/checkout@v3

      - name: Use OCaml ${{ matrix.ocaml-compiler}}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - name: Install deps
        run: opam install . --deps-only --with-test

      - name: Build
        run: opam exec -- dune build

      - name: Copy built PPX file
        run: |
          mv ./_build/default/bin/bin.exe ppx.exe

      - name: (only on release) Upload artifacts ${{ matrix.os }}
        uses: actions/upload-artifact@master
        with:
          name: ${{ matrix.os }}
          path: src/ppx.exe
          if-no-files-found: error
